---
title: "Weekly Eviction Update"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

## Eviction

```{r setup, include=FALSE}


library(tidyverse)
library(plotly)
library(readxl)
library(lubridate)


eviction_analysis_tbl <- read_excel("C:/Users/sean.finnegan/OneDrive - City of Philadelphia/Documents/Eviction Filing Tracker 09.27.2024.xlsx", 
                                              sheet = "Weekly Filing Count", range = "A6:D146", col_names = c("week", 
                                                                                                             "total_eviction_filing_count", 
                                                                                                             "percent_change_from_last_week", 
                                                                                                             "increase_or_decrease")) 


# split column one into two dates, start and end dates of the week
evictiontbl <- separate(eviction_analysis_tbl, week, c("start_date", "end_date"), sep = " - ")
evictiontbl$start_date <- trimws(evictiontbl$start_date)
evictiontbl$end_date <- trimws(evictiontbl$end_date)

# change data class
evictiontbl$total_eviction_filing_count <- as.double(evictiontbl$total_eviction_filing_count)
evictiontbl$week_of <- mdy(evictiontbl$start_date)
evictiontbl$end_date <- mdy(evictiontbl$end_date)

evictiontbl <- tibble(evictiontbl)



#set a ggplot theme
theme_set(theme(plot.title = element_text(hjust= 0, face="bold", size = 15),
                plot.background=element_rect(fill="#f7f7f7", color = "#f7f7f7"),
                panel.background=element_rect(fill = "#f7f7f7", color = NA),
                panel.grid.minor=element_blank(),
                panel.grid.major.y=element_line(color = "#cfcfcf"),
                panel.grid.major.x=element_blank(),
                axis.ticks=element_blank(),
                legend.position="top",
                panel.border=element_blank(),
                text = element_text(size=13, family="serif")))
```





```{r, include=FALSE}
# read in avg weekly filings from 2016-2019 fluxuating by week
avgweekly <- read.csv("C:/Users/Sean.finnegan/OneDrive - City of Philadelphia/Documents/avgweeklyfilings.csv")

#extract actual filings from the eviction dataframe 
evictionfilings <- evictiontbl$total_eviction_filing_count
#extract weeks from eviction dataframe
weekof <- evictiontbl$week_of

#create data frame from these vectors
avgweekly1 <- data.frame(weekof, evictionfilings)

# create vectors from these columns
weeklyavg <- avgweekly$weeklyavg
yrweek <- avgweekly$yrweek


avgweekly1$weeklyavg <- c(weeklyavg, rep(NA, nrow(avgweekly1)-length(weeklyavg)))
avgweekly1$yrweek <- c(yrweek, rep(NA, nrow(avgweekly1)-length(yrweek)))


new_row5 <- c(NA, NA, NA, NA)
new_row6 <- c(NA, NA, NA, NA)
avgweekly1 <- rbind(avgweekly1, new_row5, new_row6)

avgweekly1$weeklyavg <- rep_len(avgweekly1[1:53, 3], length(avgweekly1$weekof))

#avgweekly1[54, 3] <- avgweekly1[1, 3]
#avgweekly1[55, 3] <- avgweekly1[2, 3]
#avgweekly1[56, 3] <- avgweekly1[3, 3]
#avgweekly1[57, 3] <- avgweekly1[4, 3]
#avgweekly1[58, 3] <- avgweekly1[5, 3]
#avgweekly1[59, 3] <- avgweekly1[6, 3]
#avgweekly1[60, 3] <- avgweekly1[7, 3]
#avgweekly1[61, 3] <- avgweekly1[8, 3]
#avgweekly1[62, 3] <- avgweekly1[9, 3]
#avgweekly1[63, 3] <- avgweekly1[10,3]
#avgweekly1[64, 3] <- avgweekly1[11,3]
#avgweekly1[65, 3] <- avgweekly1[12,3]
#avgweekly1[66, 3] <- avgweekly1[13,3]
#avgweekly1[67, 3] <- avgweekly1[14,3]
#avgweekly1[68, 3] <- avgweekly1[15,3]
#avgweekly1[69, 3] <- avgweekly1[16,3]
#avgweekly1[70, 3] <- avgweekly1[17,3]
#avgweekly1[71, 3] <- avgweekly1[18,3]
#avgweekly1[72, 3] <- avgweekly1[19,3]
#avgweekly1[73, 3] <- avgweekly1[20,3]
#avgweekly1[74, 3] <- avgweekly1[21,3]
#avgweekly1[75, 3] <- avgweekly1[22,3]
#avgweekly1[76, 3] <- avgweekly1[23,3]
#avgweekly1[77, 3] <- avgweekly1[24,3]
#avgweekly1[78, 3] <- avgweekly1[25,3]
#avgweekly1[79, 3] <- avgweekly1[26,3]
#avgweekly1[80, 3] <- avgweekly1[27,3]
#avgweekly1[81, 3] <- avgweekly1[28,3]
#avgweekly1[82, 3] <- avgweekly1[29,3]
#avgweekly1[83, 3] <- avgweekly1[30,3]
#avgweekly1[84, 3] <- avgweekly1[31,3]
#avgweekly1[85, 3] <- avgweekly1[32,3]
#avgweekly1[86, 3] <- avgweekly1[33,3]
#avgweekly1[87, 3] <- avgweekly1[34,3]
#avgweekly1[88, 3] <- avgweekly1[35,3]
#avgweekly1[89, 3] <- avgweekly1[36,3]
#avgweekly1[90, 3] <- avgweekly1[37,3]
#avgweekly1[91, 3] <- avgweekly1[38,3]
#avgweekly1[92, 3] <- avgweekly1[39,3]
#avgweekly1[93, 3] <- avgweekly1[40,3]
#avgweekly1[94, 3] <- avgweekly1[41,3]
#avgweekly1[95, 3] <- avgweekly1[42,3]
#avgweekly1[96, 3] <- avgweekly1[43,3]
#avgweekly1[97, 3] <- avgweekly1[44,3]
#avgweekly1[98, 3] <- avgweekly1[45,3]
#avgweekly1[99, 3] <- avgweekly1[46,3]
#avgweekly1[100, 3] <- avgweekly1[47,3]
#avgweekly1[101, 3] <- avgweekly1[48,3]
#avgweekly1[102, 3] <- avgweekly1[49,3]
#avgweekly1[103, 3] <- avgweekly1[50,3]
#avgweekly1[104, 3] <- avgweekly1[51,3]
#avgweekly1[105, 3] <- avgweekly1[52,3]
#avgweekly1[106, 3] <- avgweekly1[53,3]
#avgweekly1[107, 3] <- avgweekly1[54,3]
#avgweekly1[108, 3] <- avgweekly1[55,3]
#avgweekly1[109, 3] <- avgweekly1[56,3]
#avgweekly1[110, 3] <- avgweekly1[57,3]
#avgweekly1[111, 3] <- avgweekly1[58,3]
#avgweekly1[112, 3] <- avgweekly1[59,3]
#avgweekly1[113, 3] <- avgweekly1[60,3]
#avgweekly1[114, 3] <- avgweekly1[61,3]
#avgweekly1[115, 3] <- avgweekly1[62,3]
#avgweekly1[116, 3] <- avgweekly1[63,3]
#avgweekly1[117, 3] <- avgweekly1[64,3]
#avgweekly1[118, 3] <- avgweekly1[65,3]
#avgweekly1[119, 3] <- avgweekly1[66,3]
#avgweekly1[120, 3] <- avgweekly1[67,3]
#avgweekly1[121, 3] <- avgweekly1[68,3]
#avgweekly1[121, 3] <- avgweekly1[69,3]
#avgweekly1[122, 3] <- avgweekly1[70,3]
#avgweekly1[123, 3] <- avgweekly1[71,3]
#avgweekly1[124, 3] <- avgweekly1[72,3]
#avgweekly1[125, 3] <- avgweekly1[73,3]
#avgweekly1[126, 3] <- avgweekly1[74,3]
#avgweekly1[127, 3] <- avgweekly1[75,3]

avgweekly1$evictionfilings <- c(NA, head(avgweekly1$evictionfilings, -1))
avgweekly1$weekof <- c(as.Date(NA), head(as.Date(avgweekly1$weekof), -1))


```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=9.25,fig.height=6}
# create an interactive plot
ggplotly(
  ggplot(avgweekly1, aes(x = weekof, y = evictionfilings)) +
      geom_line(color = "red") +
      #geom_smooth(method = "lm", se = F, color = "red") +
      ylim(c(0,600)) +
      xlab("week") +
      ylab("") +
      labs(title = "Number of Eviction filings per week", caption = "Note: The dotted line represents average weekly pre-pandemic eviction filings") +
      scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
      theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1)) +
      geom_line(aes(y = weeklyavg), linetype = 2)
  ) %>% 
  layout(title = list(text = paste0('Number of Eviction filings per week, Jan 2022 - Present',
                                    '<br>',
                                    '<sup>',
                                    'Note: The dotted line represents average weekly pre-pandemic filings',
                                    '</sup>')))
```

```{r  echo=FALSE, warning=FALSE, message=FALSE}
# create an interactive plot
ggplotly(
  ggplot(avgweekly1, aes(x = weekof, y = evictionfilings)) +
      geom_line(color = "red") +
      #geom_smooth(method = "lm", se = F, color = "red") +
      ylim(c(0,600)) +
      xlab("week") +
      ylab("") +
      labs(title = "Number of Eviction filings per week", caption = "Note: The dotted line represents average weekly pre-pandemic eviction filings") +
      scale_x_date(date_breaks = "1 month", date_labels = "%b %Y", limits = c(as.Date(Sys.Date() - 180), Sys.Date())) +
      theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
            panel.grid.major.x = element_line(color = "#cfcfcf")) +
      geom_line(aes(y = weeklyavg), linetype = 2)
  ) %>% 
  layout(title = list(text = paste0('Number of Eviction filings per week, Past 6 Months',
                                    '<br>',
                                    '<sup>',
                                    'Note: The dotted line represents average weekly pre-pandemic filings',
                                    '</sup>')))
```

## Default Judgements


```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=9.25,fig.height=6}
# create an interactive plot
ggplotly(
  ggplot(evictiontbl, aes(x = week_of, y = total_eviction_filing_count)) +
      geom_line(color = "red") +
      geom_smooth(method = "lm", se = F, color = "red", size = 0.5) +
      ylim(0, 500) +
      xlab("week") +
      ylab("") +
      labs(title = "Number of Eviction filings per week", caption = "Note: The dotted line represents average weekly pre-pandemic eviction filings") +
      scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
      theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1)) +
      geom_hline(yintercept = 405, linetype = 2)
  ) %>% 
  layout(title = list(text = paste0('Number of Eviction filings per week, Jan 2022 - Present',
                                    '<br>',
                                    '<sup>',
                                    'Note: The dotted line represents average weekly pre-pandemic filings',
                                    '</sup>')))

       
```


```{r include=FALSE}
lt_results_by_month_1_22_23 <- read_excel("C:/Users/Sean.finnegan/OneDrive - City of Philadelphia/Documents/lt-results-by-month (2).xlsx", 
                                          sheet = "Sheet1")


theme_set(theme(plot.title = element_text(hjust= 0, face="bold", size = 15),
                plot.background=element_rect(fill="#f7f7f7", color = "#f7f7f7"),
                panel.background=element_rect(fill = "#f7f7f7", color = NA),
                panel.grid.minor=element_blank(),
                panel.grid.major.y=element_line(color = "#cfcfcf"),
                panel.grid.major.x=element_blank(),
                axis.ticks=element_blank(),
                legend.position="top",
                panel.border=element_blank(),
                text = element_text(size=13, family="serif")))

lt_results_by_month_1_22_23$date <- as.Date(lt_results_by_month_1_22_23$date)


```

```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=6.25,fig.height=6}
ggplotly(
  ggplot(lt_results_by_month_1_22_23) +
  geom_rect(aes(xmin = as.Date("2024-05-01", "%Y-%m-%d"), xmax = as.Date("2024-08-01", "%Y-%m-%d"), ymin=0, ymax=100), fill='pink', alpha=0.4) + 
  geom_line(aes(x = date, y = average * 100), linetype = 2) +
  geom_line(aes(x = date, y = current_year * 100), color = "red") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  scale_y_continuous(limits = c(0, 100), breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)) +
  geom_vline(xintercept = as.numeric(as.Date("2023-01-01")), linetype = 3) +
  annotate(geom = "text", label = "â† Expanded Number of Courtrooms", y = 93, x = as.Date("2023-08-01")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1)) +
  xlab("Month") +
  ylab("%") +
  labs(title ="Default Judgement rate")
  ) %>%
  layout(title = list(text = paste0('Default Judgement rate',
                                    '<br>',
                                    '<sup>',
                                    '*The dotted line represents average monthly default judgement rate for the past 5 years',
                                    '<br>',
                                    '**Numbers for months in the shaded area have not been finalized due to a lag in the data',
                                    '</sup>')))

```
